import express from 'express';
import { signup, login, logout, getMe } from '../controllers/auth.controller.js';
import { protectRoute } from '../middleware/protectRoute.js';
const router= express.Router();



//.........authentication routes...............

router.get("/me",protectRoute,getMe); //route to check that user is authenticated or not....
router.post("/signup",signup)   //route for signup the user...
router.post("/login",login)   //route for login the user....
router.post("/logout",logout) //route for logout the user...

export default router;